spring.application.name=controle-acessos

# Aqui está a mágica: adicionamos o createDatabaseIfNotExist=true
spring.datasource.url=jdbc:mysql://localhost:3306/gatekeeper_db?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC

# Variáveis de ambiente para proteger as credenciais e evitar conflitos:
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true