spring.application.name=controle-acessos

# 1. Nova URL do Aiven (Note o ssl-mode=REQUIRED no final)
spring.datasource.url=jdbc:mysql://mysql-29bc671-gatekeeper-carla.d.aivencloud.com:10770/defaultdb?ssl-mode=REQUIRED

# 2. Credenciais do Aiven (Usando as variáveis para segurança, mas com os valores do Aiven como padrão)
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_sABGQRUzXpXyhGTv5Em

# 3. Driver e Hibernate (Mantemos o seu padrão)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# 4. Flyway (Isso vai criar suas tabelas no Aiven automaticamente)
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# 5. Segurança
api.security.token.secret=12345678